"""Parser-neutral retrieval entry points built on a finalized SoftDoc."""

from softdoc.retrieval.bm25 import BM25Index
from softdoc.retrieval.cache import (
    EmbeddingCache,
    EmbeddingCacheError,
    FileEmbeddingCache,
    MemoryEmbeddingCache,
)
from softdoc.retrieval.dense import DenseIndex
from softdoc.retrieval.encoder import (
    DenseEncoderError,
    DenseInputTooLongError,
    DenseModelUnavailableError,
    HuggingFaceE5Encoder,
    TextEncoder,
    e5_prefixed_text,
    resolve_dense_device,
)
from softdoc.retrieval.exact import ExactAnchorLookup
from softdoc.retrieval.models import (
    AnchorKind,
    AnchorResolution,
    AnchorResolutionStatus,
    AnchorTargetHandle,
    AnchorTargetType,
    ExactAnchorMatch,
    ExactLookupResult,
    ExactLookupTraceEntry,
    BM25Config,
    BM25ElementCandidate,
    BM25SearchResult,
    BM25TraceEntry,
    DenseConfig,
    DenseDevice,
    DenseElementCandidate,
    DenseSearchResult,
    DenseSegment,
    DenseTraceEntry,
    EmbeddingCacheKey,
    EmbeddingCacheRecord,
    EncoderFingerprint,
    EncoderInputType,
    EncoderTokenSpan,
    MatchedOffset,
    SearchUnit,
    SearchUnitBuildResult,
    SearchUnitConfig,
    SkippedSearchElement,
    SubQuestionInput,
)
from softdoc.retrieval.units import SearchUnitBuilder, html_to_text

__all__ = [
    "AnchorKind",
    "AnchorResolution",
    "AnchorResolutionStatus",
    "AnchorTargetHandle",
    "AnchorTargetType",
    "BM25Config",
    "BM25ElementCandidate",
    "BM25Index",
    "BM25SearchResult",
    "BM25TraceEntry",
    "DenseConfig",
    "DenseDevice",
    "DenseElementCandidate",
    "DenseEncoderError",
    "DenseIndex",
    "DenseInputTooLongError",
    "DenseModelUnavailableError",
    "DenseSearchResult",
    "DenseSegment",
    "DenseTraceEntry",
    "EmbeddingCache",
    "EmbeddingCacheError",
    "EmbeddingCacheKey",
    "EmbeddingCacheRecord",
    "EncoderFingerprint",
    "EncoderInputType",
    "EncoderTokenSpan",
    "ExactAnchorLookup",
    "ExactAnchorMatch",
    "ExactLookupResult",
    "ExactLookupTraceEntry",
    "MatchedOffset",
    "FileEmbeddingCache",
    "HuggingFaceE5Encoder",
    "MemoryEmbeddingCache",
    "SearchUnit",
    "SearchUnitBuildResult",
    "SearchUnitBuilder",
    "SearchUnitConfig",
    "SkippedSearchElement",
    "SubQuestionInput",
    "TextEncoder",
    "e5_prefixed_text",
    "resolve_dense_device",
    "html_to_text",
]
