"""Soft document intermediate representation."""

from softdoc.floating_sections import (
    FloatingContentSectionResolver,
    SectionResolutionDecision,
    SectionResolutionStatus,
)
from softdoc.hierarchy import (
    HeadingAction,
    HeadingDecision,
    HeadingHierarchyBuilder,
    HeadingHierarchyResult,
)
from softdoc.eligibility import (
    HeadingEligibilityDecision,
    HeadingEligibilityDetector,
)
from softdoc.normalization import (
    ElementNormalizationDecision,
    ElementNormalizer,
)
from softdoc.profiles import (
    DocumentProfile,
    DocumentProfileDecision,
    DocumentProfileDetector,
)
from softdoc.models import (
    BoundingBox,
    Document,
    Element,
    ElementType,
    Page,
    PageLabelCandidate,
    PageLabelSource,
    PageLabelStatus,
    Provenance,
    Relation,
    RelationEvidence,
    RelationSource,
    RelationStatus,
    RelationType,
    Section,
)
from softdoc.pipeline import (
    CoverageRecoveryPass,
    DocumentPass,
    FloatingSectionPass,
    PassContext,
    PassReport,
    PageLabelPass,
    PipelineResult,
    RelationPass,
    RuleAuditPass,
    SoftDocPipeline,
    StructurePass,
    TableFragmentReconciliationPass,
    ValidationPass,
)
from softdoc.page_labels import (
    PageLabelDecision,
    PageLabelResolutionResult,
    PageLabelResolver,
)
from softdoc.repetition import (
    RepeatedHeaderFooterDetector,
    RepeatedHeaderFooterResult,
    RepeatedRegion,
    RepeatedRegionDecision,
)
from softdoc.sections import SectionBuilder
from softdoc.structure import SoftDocumentStructureBuilder, StructureBuildResult
from softdoc.table_view import (
    TableCell,
    TableMaterializer,
    TableView,
    TableViewBuildResult,
    TableViewIssue,
    TableViewIssueCode,
    TableVisualAsset,
    TableVisualAssetSource,
)
from softdoc.table_fragments import (
    TableFragmentAssignment,
    TableReconciliationDecision,
    TableReconciliationResult,
    TableReconciliationStatus,
    reconcile_mineru_aggregate_tables,
)

__all__ = [
    "BoundingBox",
    "Document",
    "Element",
    "ElementType",
    "Page",
    "PageLabelCandidate",
    "PageLabelSource",
    "PageLabelStatus",
    "PageLabelDecision",
    "PageLabelResolutionResult",
    "PageLabelResolver",
    "Provenance",
    "Relation",
    "RelationEvidence",
    "RelationSource",
    "RelationStatus",
    "RelationType",
    "Section",
    "HeadingAction",
    "HeadingDecision",
    "HeadingHierarchyBuilder",
    "HeadingHierarchyResult",
    "HeadingEligibilityDecision",
    "HeadingEligibilityDetector",
    "ElementNormalizationDecision",
    "ElementNormalizer",
    "DocumentProfile",
    "DocumentProfileDecision",
    "DocumentProfileDetector",
    "RepeatedHeaderFooterDetector",
    "RepeatedHeaderFooterResult",
    "RepeatedRegion",
    "RepeatedRegionDecision",
    "SectionBuilder",
    "SoftDocumentStructureBuilder",
    "StructureBuildResult",
    "FloatingContentSectionResolver",
    "SectionResolutionDecision",
    "SectionResolutionStatus",
    "CoverageRecoveryPass",
    "DocumentPass",
    "FloatingSectionPass",
    "PassContext",
    "PassReport",
    "PageLabelPass",
    "PipelineResult",
    "RelationPass",
    "RuleAuditPass",
    "SoftDocPipeline",
    "StructurePass",
    "TableFragmentReconciliationPass",
    "ValidationPass",
    "TableCell",
    "TableMaterializer",
    "TableView",
    "TableViewBuildResult",
    "TableViewIssue",
    "TableViewIssueCode",
    "TableVisualAsset",
    "TableVisualAssetSource",
    "TableFragmentAssignment",
    "TableReconciliationDecision",
    "TableReconciliationResult",
    "TableReconciliationStatus",
    "reconcile_mineru_aggregate_tables",
]
